export const CursoActionTypes = {
    SET_TITLE : 'SET_TITLE',
    SET_MODAL : 'SET_MODAL',
    SET_DURACION : 'SET_DURACION',
    SET_DESCRIPCION : 'SET_DESCRIPION',
    INSERT_MODULO : 'INSERT_MODULO',
    SET_CURRENT_MODULO : 'SET_CURRENT_MODULO',
    SET_IMAGE : 'SET_IMAGE',
    SET_ALGO : 'SET_ALGO'

}